### PR TITLE
Use rgb crate

### PR DESCRIPTION
**Pull request by novedevo**
this is of course a breaking change. up to you whether you want to merge it or not. take anything you want from here

### CODE REVIEW

**Comment by novedevo** [comment]
git is hard. i undid my breaking that caused this. you can also just close this if you want

**Comment by novedevo** [comment]
maybe things are still broken. idk the old commit is there in the force push description

**Comment by gennyble** [comment]
I've been thinking about this for awhile and I think i'm okay relying on the rgb crate. However, for some reason cannot let go of my plain byte arrays as image data *(perhaps letting myself get in the way here is not a good way to write software)*, so I'll try and write an enum over it so the functions can take `<D: Into<ImageData>>`. So you can pass an `&[RGB]` or `&[u8]` and it'll handle it the same somehow. Thank you for updating this PR to main, too, I appreciate it.

**Comment by gennyble** [comment]
It looks like the RGBing was indeed lost. I reimplemented it and added you as a co-author. Sorry it took me so long to accept this.

I think having a good interop crate is important i'm just too-attached to my "plain old data" as `rgb` calls it.

I'll merge this to main and comment the commit hash here when I do, and then close this.

*(i agree git /is/ hard)*

**Pull request merged**
